server:
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.124.46.22:3306/j18_db?rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 19980123
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:**
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: utf-8

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:top/philxin/mapper/*.xml
  type-aliases-package: top.philxin.bean
  type-handlers-package: top.philxin.typehandler


